SET(OSGSOL_RELEASE_DESCRIPTOR
    "${CMAKE_SOURCE_DIR}/packaging/osgsol_release.env")
IF(NOT EXISTS "${OSGSOL_RELEASE_DESCRIPTOR}")
    MESSAGE(FATAL_ERROR
        "Canonical osgSol release descriptor is missing: ${OSGSOL_RELEASE_DESCRIPTOR}")
ENDIF()

SET(_OSGSOL_RELEASE_KEYS
    OSGSOL_PRODUCT_VERSION
    OSGSOL_SCIENCE_PHASE
    OSGSOL_PRODUCT_NAME
    OSGSOL_BUNDLE_ID)
FILE(STRINGS "${OSGSOL_RELEASE_DESCRIPTOR}" _OSGSOL_RELEASE_LINES)
FOREACH(_OSGSOL_RELEASE_LINE ${_OSGSOL_RELEASE_LINES})
    IF(NOT "${_OSGSOL_RELEASE_LINE}" MATCHES "^([A-Z0-9_]+)=(.+)$")
        MESSAGE(FATAL_ERROR
            "Malformed osgSol release descriptor line: ${_OSGSOL_RELEASE_LINE}")
    ENDIF()
    SET(_OSGSOL_RELEASE_KEY "${CMAKE_MATCH_1}")
    SET(_OSGSOL_RELEASE_VALUE "${CMAKE_MATCH_2}")
    LIST(FIND _OSGSOL_RELEASE_KEYS "${_OSGSOL_RELEASE_KEY}"
         _OSGSOL_RELEASE_KEY_INDEX)
    IF(_OSGSOL_RELEASE_KEY_INDEX EQUAL -1)
        MESSAGE(FATAL_ERROR
            "Unknown osgSol release descriptor key: ${_OSGSOL_RELEASE_KEY}")
    ENDIF()
    IF(DEFINED _OSGSOL_RELEASE_SEEN_${_OSGSOL_RELEASE_KEY})
        MESSAGE(FATAL_ERROR
            "Duplicate osgSol release descriptor key: ${_OSGSOL_RELEASE_KEY}")
    ENDIF()
    SET(_OSGSOL_RELEASE_SEEN_${_OSGSOL_RELEASE_KEY} TRUE)
    SET(${_OSGSOL_RELEASE_KEY} "${_OSGSOL_RELEASE_VALUE}")
ENDFOREACH()

FOREACH(_OSGSOL_RELEASE_KEY ${_OSGSOL_RELEASE_KEYS})
    IF(NOT DEFINED _OSGSOL_RELEASE_SEEN_${_OSGSOL_RELEASE_KEY})
        MESSAGE(FATAL_ERROR
            "Missing osgSol release descriptor key: ${_OSGSOL_RELEASE_KEY}")
    ENDIF()
ENDFOREACH()

IF(NOT OSGSOL_PRODUCT_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    MESSAGE(FATAL_ERROR "Invalid osgSol product version: ${OSGSOL_PRODUCT_VERSION}")
ENDIF()
IF(NOT OSGSOL_SCIENCE_PHASE MATCHES "^G[0-9]+\\.[0-9]+$")
    MESSAGE(FATAL_ERROR "Invalid ScienceEarth phase: ${OSGSOL_SCIENCE_PHASE}")
ENDIF()
IF(NOT OSGSOL_PRODUCT_NAME STREQUAL "osgSol Earth")
    MESSAGE(FATAL_ERROR "The fixed product name must remain osgSol Earth")
ENDIF()
IF(NOT OSGSOL_BUNDLE_ID MATCHES "^[A-Za-z0-9.-]+$")
    MESSAGE(FATAL_ERROR "Invalid osgSol bundle id: ${OSGSOL_BUNDLE_ID}")
ENDIF()

UNSET(_OSGSOL_RELEASE_KEY)
UNSET(_OSGSOL_RELEASE_KEY_INDEX)
UNSET(_OSGSOL_RELEASE_KEYS)
UNSET(_OSGSOL_RELEASE_LINE)
UNSET(_OSGSOL_RELEASE_LINES)
UNSET(_OSGSOL_RELEASE_VALUE)
